services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - source: mongodb # Host path /var/lib/docker/volumes/mongodb
        target: /data/db # Container path
        type: volume

  redis:
    image: redis
    container_name: redis
    volumes:
      - source: redis
        target: /data
        type: volume

  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - source: rabbitmq
        target: /var/lib/rabbitmq
        type: volume

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  
  user:
    image: user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - user
      - cart
  
  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - redis
      - mysql
      - rabbitmq
      - catalogue
      - user
      - cart
      - shipping
      - payment

networks:
  default:
    external:
      name: roboshop

# Below steps similar to docker volume create <mongodb> command
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
