services:
  mongodb:
    image: mongodb:1
    container_name: mongodb
  redis:
    image: redis
  mysql:
    image: mysql:1
    container_name: mysql
  catalogue:
    image: catalogue:1
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    image: user:1
    container_name: user
    depends_on:
      - mongodb
  web:
    image: web:1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - catalogue

networks:
  default:
    external:
      name: roboshop